### ISSUE TITLE
Typo and Paste in blocks

### ISSUE THREAD

**Issue by cafecitopuro** [philippoehrlein/typo-and-paste#14]
Does this plug-in work with Kirby's text block? It doesn't seem to, but maybe I've not configured it correctly? Using the `opt+T` menu, I can't insert any characters into the text block, nor does the plugin seem to support adding a button to the text block's context menu that appears when the user highlights content within the block.

**Comment by philippoehrlein** [comment]
hey there,
you can add the button to a custom textblock like this:
```yml
fields:
  blocks:
    label: Blocks
    type: blocks
    fieldsets:
      custom:
        wysiwyg: true
        preview: text
        fields:
          text:
            type: writer
            label: Text
            toolbar:
              inline: true
              marks:
                - bold
                - italic
                - underline
                - strike
                - code
                - '|'
                - typo-and-paste
```

Add the moment, the plugin only adds the characters into your clipboard.
